### ISSUE TITLE
第7章开始就没有汉化了,包括主对话在内都没有汉化了

### ISSUE THREAD

**Issue by penghei** [Vetoyi/CN_Patch.Being_A_DIK#1]
我看readme上说78章是机翻,而且是部分汉化,但是我这里整个7 8 章都没有汉化

**Comment by Vetoyi** [comment]
请确认你当前使用的是0.08版还是0.09版补丁：0.08版请到游戏内的设置中启用“简体中文”选项；0.09版默认启用简体中文。

**Comment by penghei** [comment]
OK 重启之后就有了 感谢

**Comment by 1ce0818** [comment]
大佬，解压密码是什么啊，找了个遍没找到，感谢
