### ISSUE TITLE
求助 5-8汉化失效

### ISSUE THREAD

**Issue by zoraShi** [Vetoyi/CN_Patch.Being_A_DIK#11]
如题，另，不太清楚能不能把对话文本变成文本文件让程序动态获取，这样应该可以协助您完成翻译工作，尤其是在现在的Ai时代

**Comment by zoraShi** [comment]
已解决，是我删除了session 2部分的文件，参照了没购买session2的方式，抱歉

**Comment by Vetoyi** [comment]
> 如题，另，不太清楚能不能把对话文本变成文本文件让程序动态获取，这样应该可以协助您完成翻译工作，尤其是在现在的Ai时代

文件或excel形式来进行AI翻译是可行的，年初的时候就有想过但当时没找到有大佬做相关工具，而现在有了并且很好用最近也试了一下，还是会有机翻的痕迹但至少整体会比纯机翻的要好，所以未来如果有空会给没有汉化的游戏出点AI翻译补丁，至于多久就是另一回事了...精度也是依旧没法保障。

**Comment by zoraShi** [comment]
@Vetoyi 很感谢您为这个游戏的付出，确实是个好游戏，讲了一个很好的故事，可惜官方对于汉化的态度真是让人很失望；我其实想说的意思是，有没有可能让游戏编译后读取本地的文本或者excel，这样您就可以分2个部分维护您的补丁了，一部分是以读取的形式，读取原对白文件的让对白外挂的补丁，另一部分就是纯文本的对白，这个对白的部分可以放出来，看看有没有其他有兴趣的贡献者，自己去基于一些ai模型协助您进行翻译，当然如果可以做到这个程度，我也觉得您应该找开发者们谈谈，毕竟您已经为“纯爱“付出太多，再次感谢您的付出，让我领略了一个好故事
