### ISSUE TITLE
大佬你好，我想跟你一起翻译

### ISSUE THREAD

**Issue by San7az** [Vetoyi/CN_Patch.Being_A_DIK#12]
如题，想了解一下做这种汉化补丁的具体流程，你看可以互相了解一下吗

**Comment by Vetoyi** [comment]
不是大佬啦，可以先留个联系方式，不过其实Renpy汉化流程早在知乎或是B站就都已经有大佬出过完整教程了，所以能分享的说实话也不是很多，只是单纯追求产出机翻、AI汉化的话其实很简单，精翻就得看个人了像我这样水平菜又不想花那么多个人时间的就纯摆了。

**Comment by San7az** [comment]
加我微信吧 Zirinic7 正好考完研了闲的没事可以搞一搞哈哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vetoyi/CN_Patch.Being_A_DIK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月26日(星期二) 晚上7:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vetoyi/CN_Patch.Being_A_DIK] 大佬你好，我想跟你一起翻译 (Issue #12)





 
不是大佬啦，可以先留个联系方式，不过其实Renpy汉化流程早在知乎或是B站就都已经有大佬出过完整教程了，所以能分享的说实话也不是很多，只是单纯追求产出机翻、AI汉化的话其实很简单，精翻就得看个人了像我这样水平菜又不想花那么多个人时间的就纯摆了。
