### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by WANG12124558** [Vetoyi/CN_Patch.Being_A_DIK#14]
安装以后游戏打不开，安装了三次了，按流程操作的

**Comment by WANG12124558** [comment]
仅那两个文件解压至D:\steam\steamapps\common\Being a DIK 文件夹，但是打不开游戏

**Comment by Vetoyi** [comment]
先留个qq，有空的时候再远程操作一下

**Comment by Vetoyi** [comment]
实际为缺少Season2 DLC但没有删除对应的Season2补丁文件，导致无法运行游戏，删除对应文件/购买安装S2 DLC即可解决。

**Comment by WANG12124558** [comment]
谢谢，问题已经解决
