### ISSUE TITLE
大佬，0.83的解压密码是什么？不是BAD

### ISSUE THREAD

**Issue by zwhnhy** [Vetoyi/CN_Patch.Being_A_DIK#7]

**Comment by Vetoyi** [comment]
要认真看github库的当前补丁说明呀，都有写解压码的。
0.82只是因为当初设的是BAD和如今的不一样，所以才单独注明在标题上，以防有人需要但不知道解压码。

**Comment by Vetoyi** [comment]
然后0.83目前文件的解压码是vetoy
